In [1]:
import gym
from gym.vector import make

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

from tqdm import tqdm
from IPython.display import clear_output
import matplotlib.pyplot as plt

from utils.network import Linear, Sequential
import random

from tqdm import tqdm

In [37]:
env = make('HalfCheetah-v4', num_envs=8, render_mode="rgb_array")
obs, _ = env.reset()


for _ in tqdm(range(1000)):  # Run for 100 timesteps
    # Take random actions for each environment instance
    actions = env.action_space.sample()
    
    # Step through the environment
    obs, rewards, terminated, truncated, infos = env.step(actions)
    
    # Print information
    # print("obs:", obs)
    # print("Rewards:", rewards)
    # print("Dones:", dones)
    # print("Infos:", infos)
    
    # # Check if any environments are done
    # if dones.any():
    #     print("Resetting environments that are done...")
    #     obs, _ = env.reset(np.where(dones)[0])

  0%|          | 0/1000 [00:00<?, ?it/s]/home/nazim/.local/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
100%|██████████| 1000/1000 [00:00<00:00, 1939.26it/s]


In [1]:
import gym
from gym.vector import SyncVectorEnv
import numpy as np
from tqdm import tqdm

In [14]:
# Define the environment creation functions
env_fns = [lambda: gym.make('HalfCheetah-v4', render_mode="rgb_array") for _ in range(2)]

# Create the SyncVectorEnv with 8 parallel environments
env = SyncVectorEnv(env_fns)
obs = env.reset()

for _ in tqdm(range(1000)):  # Run for 1000 timesteps
    # Sample random actions for each environment instance
    actions = np.array([env.single_action_space.sample() for _ in range(env.num_envs)])
    
    # Step through the environments
    obs, rewards, terminated, truncated, infos = env.step(actions)
    
    
    # # Check if any environments are done
    # if np.any(terminated) or np.any(truncated):
    #     # Reset only the environments that are done
    #     envs_to_reset = np.where(terminated | truncated)[0]
    #     new_obs = env.reset(envs_to_reset)
    #     obs[envs_to_reset] = new_obs  # Update obs with the reset ones


100%|██████████| 1000/1000 [00:00<00:00, 8570.98it/s]


In [14]:
import brax
import jax
import jax.numpy as jnp
from brax.envs import create

# Create the HalfCheetah environment
env = create(env_name='ant', debug=True, backend='mjx')
key = jax.random.PRNGKey(0)  # Initialize the random key
state = env.reset(key)

# Run a simple loop with random actions
for _ in range(100):
    key, subkey = jax.random.split(key)
    action = jax.random.uniform(subkey, shape=(env.action_size,), minval=-1.0, maxval=1.0)
    state = env.step(state, action)
    # print(f"Position: {state.qp.pos}, Velocity: {state.qp.vel}, Reward: {state.reward}")
    print(state.pipeline_state.contact)
    break
# You can access more details about the environment
print("Observation size:", env.observation_size)
print("Action size:", env.action_size)


XlaRuntimeError: INTERNAL: cuSolver internal error

In [20]:
env.sys.ngeom

18

In [12]:
state.info.keys()

dict_keys(['first_obs', 'first_pipeline_state', 'steps', 'truncation'])

In [13]:
brax

<module 'brax' from '/home/nazim/.local/lib/python3.10/site-packages/brax/__init__.py'>

In [10]:
state.pipeline_state.contact.__dir__()

['dist',
 'pos',
 'frame',
 'includemargin',
 'friction',
 'solref',
 'solreffriction',
 'solimp',
 'dim',
 'geom1',
 'geom2',
 'geom',
 'efc_address',
 'link_idx',
 'elasticity',
 '__module__',
 '__annotations__',
 '__doc__',
 '__dataclass_params__',
 '__dataclass_fields__',
 '__init__',
 '__repr__',
 '__eq__',
 '__setattr__',
 '__delattr__',
 '__hash__',
 '__match_args__',
 'replace',
 '__init_subclass__',
 'fields',
 'tree_replace',
 '__dict__',
 '__weakref__',
 '__new__',
 '__str__',
 '__getattribute__',
 '__lt__',
 '__le__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__reduce_ex__',
 '__reduce__',
 '__subclasshook__',
 '__format__',
 '__sizeof__',
 '__dir__',
 '__class__',
 '__add__',
 '__sub__',
 '__mul__',
 '__neg__',
 '__truediv__',
 'reshape',
 'select',
 'slice',
 'take',
 'concatenate',
 'index_set',
 'index_sum',
 'vmap',
 'T',
 '_flax_dataclass']

In [5]:
import brax
import jax
import jax.numpy as jnp
from brax.envs import create

# Create the HalfCheetah environment
env = create(env_name='halfcheetah')
key = jax.random.PRNGKey(0)  # Initialize the random key
state = env.reset(key)

# JIT compile the step function for faster performance
jit_step = jax.jit(env.step)


None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
Observation size: 17
Action size: 6


In [8]:

# Run a simple loop with random actions
for _ in range(1000):
    key, subkey = jax.random.split(key)
    action = jax.random.uniform(subkey, shape=(env.action_size,), minval=-1.0, maxval=1.0)
    state = jit_step(state, action)  # Use the JIT-compiled step
    # print(f"Position: {state.qp.pos}, Velocity: {state.qp.vel}, Reward: {state.reward}")
    # print(state.pipeline_state.contact)

# You can access more details about the environment
print("Observation size:", env.observation_size)
print("Action size:", env.action_size)


Observation size: 17
Action size: 6


In [3]:
obs

array([[ -0.10528024,   0.85361652,  -0.30795678, ...,   3.77239866,
        -17.20474988,  13.56826719],
       [ -0.5404349 ,   3.33156089,   0.08875557, ...,   9.44116568,
         -4.96446806,  -0.87808777],
       [  0.05814471,   0.08896324,   0.1109116 , ...,  -6.81672797,
          2.49000965,   2.3275792 ],
       ...,
       [ -0.09578597,   0.20662664,  -0.39879245, ...,  -0.54758868,
         -3.07707887,  -4.07165926],
       [ -0.131607  ,   0.14488677,  -0.34199292, ...,  10.35181668,
        -13.33417952,  -3.41434841],
       [ -0.57572957,   3.30456687,   0.26041024, ...,   9.22364236,
         -9.313844  ,   3.91076384]])

In [1]:
# Define the environment creation functions
import gym
from tqdm import tqdm
import numpy as np

env_fns = [lambda: gym.make('HalfCheetah-v4', render_mode="rgb_array") for _ in range(64)]

# Create the SyncVectorEnv with 8 parallel environments
env = gym.vector.SyncVectorEnv(env_fns)
obs = env.reset()

for _ in tqdm(range(1000)):  # Run for 1000 timesteps
    # Sample random actions for each environment instance
    actions = np.array([env.single_action_space.sample() for _ in range(env.num_envs)])
    
    # Step through the environments
    obs, rewards, terminated, truncated, infos = env.step(actions)
    
    # print(env.envs[0].data.contact.dist)
    # print(env.envs[0].data.contact)
    # print('\n\n\n')


  0%|          | 0/1000 [00:00<?, ?it/s]/home/nazim/.local/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
 94%|█████████▎| 936/1000 [00:02<00:00, 320.94it/s]


KeyboardInterrupt: 

---

In [8]:
import jax
import jax.numpy as jnp
from brax import envs
from brax.io import html

# Initialize HalfCheetah environment with 2048 parallel environments
num_envs = 256
env = envs.create(env_name="halfcheetah", batch_size=num_envs)

# JIT-compiled reset function
@jax.jit
def reset_fn(key):
    return env.reset(key)

# JIT-compiled step function
@jax.jit
def step_fn(state, key):
    actions = jax.random.uniform(key, (num_envs, env.action_size), minval=-1.0, maxval=1.0)
    return env.step(state, actions)


In [9]:

# Use the reset function to get the initial state
key = jax.random.PRNGKey(0)
state = reset_fn(key)

In [10]:
from tqdm import tqdm

key = jax.random.PRNGKey(0)
# Simulate a few steps in the environment using the JIT-compiled step function
for _ in range(100):
    key, subkey = jax.random.split(key)
    state = reset_fn(subkey)
    for i in tqdm(range(1000)):
        key, subkey = jax.random.split(key)
        state = step_fn(state, subkey)
    

# Rendering one of the environments as HTML

 57%|█████▋    | 573/1000 [00:09<00:06, 62.58it/s]


KeyboardInterrupt: 

In [ ]:
html_str = html.render(env.sys, [state.qp[0]])
with open("halfcheetah_render.html", "w") as f:
    f.write(html_str)

---

In [1]:
#@title Import Brax and some helper modules
from IPython.display import clear_output

import collections
from datetime import datetime
import functools
import math
import os
import time
from typing import Any, Callable, Dict, Optional, Sequence


import brax
from brax import envs
from brax.envs.wrappers import gym as gym_wrapper
from brax.envs.wrappers import torch as torch_wrapper
from brax.io import metrics
from brax.training.agents.ppo import train as ppo
import gym
import matplotlib.pyplot as plt
import numpy as np
import torch
from torch import nn
from torch import optim
import torch.nn.functional as F

from tqdm import tqdm

device = 'cuda'

In [111]:
env = envs.create('ant', batch_size=4, episode_length=1000, backend='spring', debug=True)
env = gym_wrapper.VectorGymWrapper(env)
# automatically convert between jax ndarrays and torch tensors:
env = torch_wrapper.TorchWrapper(env, device=device)

# env warmup
env.reset()
action = torch.zeros(env.action_space.shape).to(device)
env.step(action)

(tensor([[ 0.5765,  0.9968,  0.0263,  0.0492,  0.0580, -0.0198,  1.0140,  0.0597,
          -1.0661,  0.0199, -1.0266, -0.0125,  0.9343, -0.3866, -0.0275,  0.1511,
          -0.1777, -0.0584,  0.0298, -0.0306,  0.4593, -0.1089, -0.1030, -0.1458,
          -0.1245,  0.0432,  0.5491],
         [ 0.5128,  0.9944,  0.0328,  0.0342, -0.0947,  0.0898,  0.9476,  0.0073,
          -1.0514,  0.0505, -1.0007,  0.0541,  0.9415, -0.0613,  0.0527,  0.6217,
          -0.3193, -0.2521,  0.0279, -0.0197, -0.6373,  0.0354,  0.5285,  0.0194,
           0.4948,  0.0466, -0.5715],
         [ 0.4818,  0.9962, -0.0728,  0.0472, -0.0067, -0.0184,  0.9481, -0.0445,
          -0.8858,  0.0174, -0.9227,  0.0694,  1.0113,  0.0144, -0.0587,  0.1422,
           0.2087, -0.0264, -0.0165, -0.0639, -0.1278,  0.1359,  0.5828,  0.1500,
           0.0246, -0.1773, -0.6507],
         [ 0.5547,  0.9977, -0.0413,  0.0503,  0.0171, -0.0052,  0.8757, -0.0125,
          -0.9459,  0.0785, -1.0743,  0.0170,  0.8927,  0.1397,  0

In [112]:
total_reward = 0


for episode in tqdm(range(1000)):
    for _ in tqdm(range(1000)):
        # action = env.action_space.sample()  # Sample a randsom action
        action = torch.zeros(env.action_space.shape).to(device)
        observation, reward, done, _ = env.step(action)  # Take a step
        total_reward += reward
        
        # print(env.env._state.pipeline_state.contact)
        # print(env.env._state.pipeline_state.contact.geom2[0])
        if env.env._state.pipeline_state.contact.geom[..., 0].mean() != 0:
            print('wey')

  0%|          | 2/1000 [00:11<1:39:29,  5.98s/it]


KeyboardInterrupt: 

In [113]:
env.env._state.pipeline_state.contact.penetration

AttributeError: 'Contact' object has no attribute 'penetration'

In [110]:
[s for s in env.env._state.pipeline_state.contact.__dir__() if not s.startswith('__')]

['dist',
 'pos',
 'frame',
 'includemargin',
 'friction',
 'solref',
 'solreffriction',
 'solimp',
 'dim',
 'geom1',
 'geom2',
 'geom',
 'efc_address',
 'link_idx',
 'elasticity',
 'replace',
 'fields',
 'tree_replace',
 'reshape',
 'select',
 'slice',
 'take',
 'concatenate',
 'index_set',
 'index_sum',
 'vmap',
 'T',
 '_flax_dataclass']

In [81]:
env.env._state.pipeline_state.contact.geom2[0]

Array([2, 2, 3, 3, 5, 5, 6, 6, 8, 8], dtype=int32)

In [59]:
torch.tensor(np.array(env.env._state.obs)) == observation.cpu()

tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False]])

In [60]:
torch.tensor(np.array(env.env._state.obs))

tensor([[-4.4236e-01,  3.4409e-02, -1.1064e-01,  7.8540e-01,  7.8534e-01,
          2.0917e-01, -1.2007e+00, -1.8114e-02, -1.6354e-03, -3.7683e-03,
         -4.6754e-03,  3.1769e-02, -4.5038e-02, -2.7144e-03,  7.6676e-03,
         -6.7668e-03, -3.7451e-02],
        [-4.4230e-01,  3.4371e-02, -1.1086e-01,  7.8573e-01,  7.8536e-01,
          2.0899e-01, -1.2007e+00, -1.8456e-02, -1.4877e-03, -6.0901e-03,
         -3.6648e-03,  1.8008e-02, -1.1367e-03, -3.6091e-02,  6.0446e-03,
         -4.2902e-03,  5.3367e-02],
        [-3.7848e-01,  1.6521e-01, -2.8083e-01,  7.8556e-01, -4.0040e-01,
          8.4085e-02, -1.2009e+00, -2.0755e-02,  1.2994e-04,  3.1148e-03,
         -1.8267e-02,  1.8970e-02, -1.9552e-04, -2.4140e-04,  1.1868e-02,
          2.6825e-02,  4.4525e-02],
        [-4.4233e-01,  3.4478e-02, -1.1089e-01,  7.8567e-01,  7.8551e-01,
          2.0902e-01, -1.2007e+00, -1.6946e-02, -1.9821e-03, -1.7020e-03,
         -3.2149e-04, -1.4609e-02,  2.9595e-02, -3.4078e-04,  3.8172e-03,
    

In [58]:
observation

tensor([[-4.4231e-01,  3.4410e-02, -1.1087e-01,  7.8560e-01,  7.8550e-01,
          2.0904e-01, -1.2006e+00, -1.6544e-02, -2.0001e-04,  1.0259e-03,
          4.4990e-04, -9.4982e-03,  4.1753e-03,  3.4786e-02,  1.3771e-02,
         -7.7763e-03, -3.4121e-02],
        [-4.4233e-01,  3.4393e-02, -1.1083e-01,  7.8548e-01,  7.8525e-01,
          2.0899e-01, -1.2007e+00, -1.9870e-02, -3.9544e-03, -2.1494e-03,
          2.6219e-03, -1.4353e-02,  1.0301e-02,  9.6085e-03, -1.9847e-03,
          2.3208e-03,  5.3043e-03],
        [-3.7846e-01,  1.6538e-01, -2.8076e-01,  7.8548e-01, -4.0051e-01,
          8.3994e-02, -1.2010e+00, -2.3723e-02,  1.5448e-02,  2.7632e-03,
          3.4395e-04, -1.1552e-03, -2.1399e-03,  9.3480e-03, -1.6646e-02,
          1.3552e-02,  1.2266e-02],
        [-4.4233e-01,  3.4386e-02, -1.1074e-01,  7.8542e-01,  7.8540e-01,
          2.0888e-01, -1.2007e+00, -1.6546e-02, -1.9111e-03,  2.8851e-03,
          1.1574e-02,  1.8289e-02, -2.7436e-02, -8.1760e-03, -1.5469e-02,
    

---

In [5]:
from brax import envs
import jax.numpy as jp
from qdax.environments import FeetContactWrapper
from qdax import environments


# choose in ["ant", "walker2d", "hopper", "halfcheetah"]
ENV_NAME = "ant"
env = envs.create(env_name=ENV_NAME)
qd_env = FeetContactWrapper(env, ENV_NAME)

state = qd_env.reset(rng=jp.random_prngkey(seed=0))
for i in range(10):
    action = jp.zeros((qd_env.action_size,))
    state = qd_env.step(state, action)

    # retrieve feet contact
    feet_contact = state.info["state_descriptor"]

    # do whatever you want with feet_contact
    print(f"Feet contact : {feet_contact}")

AttributeError: 'System' object has no attribute 'config'

In [6]:
brax_env = environments.create(env_name="halfcheetah_uni")

In [13]:
brax_env.env.env.env.env